---
abstract: 'Processor for templates containing Perl expressions'
author:
  - 'Philippe Verdret <pverdret@dalet.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120351'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ParseTemplate
no_index:
  directory:
    - t
    - inc
requires:
  Symbol: 0
  Test::More: 0.96
version: 3.08
