--- #YAML:1.0
name:               ParseTemplate
version:            3.02
abstract:           Processor for templates containing Perl expressions
author:
    - Philippe Verdret <pverdret@dalet.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Symbol:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
